### PR TITLE
auto close mobile nav on wallet open

### PR DESCRIPTION
**Pull request by dinghino**
same fix as [#12](https://github.com/2omb/3omb-frontend/pull/12) on 3omb.

### CODE REVIEW

**Comment by 0xD4V1NC1** [comment]
@dinghino Would you mind adding  
```
display: 'flex',
justifyContent: 'center',
alignItems: 'center',
``` 
to ~line 55 in the nav.tsx file? just fixes a quick style bug in the header

Screen Shot 2022-02-14 at 4 18 17 PM

**Comment by dinghino** [comment]
added that and pulled it in sync with the new UI (couldn't solve the conflict otherwise, don't know why). should be ready to go in?

**Comment by chinochao** [comment]
Cant merge without the conflict fixed.

**Comment by chinochao** [comment]
LGTM

**Pull request merged**
